- name: Play1
  hosts: all
  tasks:
    - name: Print Task1
      ansible.builtin.debug:
        msg: "Task1"

    - name: Print task2
      ansible.builtin.debug:
        msg: "Task2"

- name: Play2
  hosts: all

  ## ansible-playbook -i ../inv -u centos -k 01.sample.playbook.yml
